language: php

php:
  - '5.6'

install:
  - travis_retry npm install
  - travis_retry npm install bower
  - travis_retry bower install
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

before_script:
  - mysql -e "CREATE DATABASE angel_test;"
  - gulp
  - cp .env.travis .env
  - php artisan key:generate

script:
  - gulp
  - phpunit