language: php

# Use MySQL 5.6
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

php:
  - 5.6
  - 7.0

install:
  - travis_retry npm install -g npm@2
  - travis_retry npm install
  - travis_retry npm install bower
  - travis_retry bower install
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

before_script:
  - mysql -u root -e "CREATE DATABASE angel_test;"
  - cp .env.travis .env
  - php artisan key:generate
  - gulp

script:
  - phpunit