language: php

php:
  - 7.1

install:
  - nvm install stable
  - nvm use stable

before_script:
  - composer self-update
  - composer install --no-interaction
  - npm install
  - npm run dev
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan testing:rebuild

script:
  - ./vendor/bin/phpunit
